name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Node.js 环境为 18
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 使用 Node 18 版本

      # 安装项目依赖
      - name: Install dependencies
        run: |
          npm install  # 安装项目的依赖

      # 构建 VitePress 静态文件
      - name: Build VitePress site
        run: |
          npm run docs:build  # 使用 npm 脚本构建静态页面，确保你的 package.json 中有 docs:build 脚本

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist  # VitePress 默认构建输出目录
