name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装依赖
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 你可以根据需要选择 Node.js 的版本

      - name: Install dependencies
        run: |
          npm install  # 安装项目的依赖

      # 构建 VitePress 静态文件
      - name: Build VitePress site
        run: |
          npm run docs:build  # 使用 VitePress 构建静态页面，确保你的 package.json 中有定义 build 脚本

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist  # 这里是 VitePress 默认的构建输出目录
